#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV 
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#98971d"
bspc config normal_border_color "#928374"

bspc rule -a Emacs state=tiled
bspc rule -a Chromium state=maximized desktop=II

#Autostart applications
polybar --config=$HOME/.config/bspwm/polybar/config.ini &
sxhkd &
picom --config $HOME/.config/bspwm/picom/picom.conf &
nitrogen --restore &
dunst &
redshift -l 1.351898:103.717214 &
